# Encoder Settings
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Battery Settings
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=60
CONFIG_ADC=n

# Bluetooth Connectivity
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

# Bluetooth (安定性向上)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
