# Encoder Settings
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Battery Settings
CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_BATTERY_REPORT_INTERVAL=300
CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER_MAX_MV=4200
CONFIG_ZMK_BATTERY_VOLTAGE_DIVIDER_MIN_MV=3300

# Bluetooth Connectivity
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6
